export enum PageStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  DETECTION_FAILED = "DETECTION_FAILED",
  SECTIONS_CONFIRMED = "SECTIONS_CONFIRMED",
  IN_TRANSLATION = "IN_TRANSLATION",
  TRANSLATED = "TRANSLATED",
  FINALIZED = "FINALIZED",
}
