export enum PageStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  DETECTION_FAILED = "DETECTION_FAILED",
  SECTIONS_CONFIRMED = "SECTIONS_CONFIRMED",
  IN_TRANSLATION = "IN_TRANSLATION",
  TRANSLATED = "TRANSLATED",
  FINALIZED = "FINALIZED",
}

export enum ReviewStatus {
  REJECTED = "REJECTED",
  NOT_STARTED = "NOT_STARTED",
  NO_TRANSLATIONS = "NO_TRANSLATIONS",
  PARTIALLY_TRANSLATED = "PARTIALLY_TRANSLATED",
  FULLY_TRANSLATED = "FULLY_TRANSLATED",
  PARTIALLY_APPROVED = "PARTIALLY_APPROVED",
  FULLY_APPROVED = "FULLY_APPROVED",
}

export enum BuildStatus {
  NONE = "NONE",
  BUILDING = "BUILDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum VersionStatus {
  DRAFT = "DRAFT",
  FINALIZED = "FINALIZED",
  ARCHIVED = "ARCHIVED",
}

export enum BookStatus {
  UPLOADING = "UPLOADING",
  READY = "READY",
}
