export enum PageStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  DETECTION_FAILED = "DETECTION_FAILED",
  SECTIONS_CONFIRMED = "SECTIONS_CONFIRMED",
  IN_TRANSLATION = "IN_TRANSLATION",
  TRANSLATED = "TRANSLATED",
  FINALIZED = "FINALIZED",
}

export enum BuildStatus {
  NONE = "NONE",
  BUILDING = "BUILDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum VersionStatus {
  DRAFT = "DRAFT",
  FINALIZED = "FINALIZED",
  ARCHIVED = "ARCHIVED",
}

export enum BookStatus {
  UPLOADING = "UPLOADING",
  READY = "READY",
}
